### ISSUE TITLE
Afegir instruccions de deploy al README

### ISSUE THREAD

**Issue by casassg** [quim-motger/asw-hackernews#20]
S'ha de afegir les instruccions de com fer deploy al README del repositori per tal de que es pugui seguir bé com usar el projecte si s'ha de configurar desde 0.

**Comment by quim-motger** [comment]
Tanco ja que el README ja disposa de la informació que es demana a Atenea:

- Nom de tots els membres de l'equip
- Link a la vostra aplicació desplegada a heroku.

Afegeixo al README que s'ha fet servir els issues per fer el tracking de problemes
