### ISSUE TITLE
Quan s'accedeix a edició d'usuari des d'un enllaç de la web, el formulari no funciona

### ISSUE THREAD

**Issue by quim-motger** [quim-motger/asw-hackernews#41]
Tot i que accedint per url a /user?id= funciona sense problemes, si s'accedeix exactament a la mateixa ruta mitjançant un enllaç a la web, el botó "update" sembla no funcionar

**Comment by casassg** [comment]
Hem modificat per evitar anar via turbolink seguint les instruccions de:  [StackOverflow](http://stackoverflow.com/questions/14227363/using-turbolinks-in-a-rails-link-to)

Queda pendent trobar una solució més correcte, però de moment solucionem el problema temporalment
